apiVersion: v1
kind: ReplicationController
metadata:
  name: web-rc
  labels:
    app: web-app-rc
    type: front-end
spec:
  template:
    metadata:
      name: web-pod
      labels:
        app: web-app-rc
        type: front-end
    spec:
      containers:
      - name: web-app
        image: nginx
  replicas: 3    
